# Generated by Django 5.2.13 on 2026-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllisting',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Shown on your listing so people can reach you.', max_length=254, verbose_name='contact email'),
        ),
    ]
